name: Upload Python Package to PyPI Test

on:
  pull_request:
    branches:
      - dev
    types: [closed]

# Use the following for when we want to publish to the official PyPI from master
#   push:
#     tags:
#       - "v*" # Will trigger for every tag, 'v*'

jobs:
  publish-test-pypi:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-in-project: true
          virtualenvs-create: true
      - name: Install dependencies
        run: |
          poetry --version
          poetry install
      - name: Build and publish
        env:
          PYPI_USERNAME: __token__
          PYPI_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: make publish_pytest
